#######################################################
## This is a code entry in the error correction zoo. ##
##       https://github.com/errorcorrectionzoo       ##
#######################################################

code_id: sharp_config
physical: spheres
logical: reals

name: 'Universally optimal spherical code'
introduced: '\cite{arxiv:math/0607446}'

description: |
  A spherical code that is a spherical design of strength \(2m-1\) for some \(m\) and that has \(m\) distances between distinct points.
  Such configurations minimize completely monotonic potentials on the sphere.
  All known universally optimal spherical codes are either obtained from the Leech or \(E_8\) lattice, certain regular polytopes, or are CGS isotropic subspace spherical codes.

relations:
  parents:
    - code_id: spherical


# Begin Entry Meta Information
_meta:
  # Change log - most recent first
  changelog:
    - user_id: VictorVAlbert
      date: '2023-02-23'
